version: '3.1'

services:
  graph:
    image: littlefisher0/cosdisk
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    entrypoint: ["/app/graphserver", "--host", "0.0.0.0", "--port", "8080"]

  ftp:
    image: littlefisher0/cosdisk
    depends_on:
    - graph
    ports:
      - "2121-2123:2121-2123"
      - "21:21" 
    entrypoint: ["/app/ftpserver"]
    

volumes:
  pg_data:
  redis_data:
  pgadmin_data:
