version: '3.1'

services:
  graph:
    image: cosdisk/backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    entrypoint: ["/app/graphserver", "--host", "0.0.0.0", "--port", "8080"]

  ftp:
    image: cosdisk/backend
    depends_on:
    - graph
    ports:
      - "2121:2121"
      - "21:21" 
    entrypoint: ["/app/ftpserver"]
    
  vue:
    image: cosdisk/frontend
    build:
      context: ./vue-project
      args:
        - GQL_BACKEND=http://127.0.0.1:8080/query
    ports:
      - "8000:80"

volumes:
  pg_data:
  redis_data:
  pgadmin_data:
