// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/Littlefisher619/cosdisk/model"
)

type AuthResult struct {
	Token string      `json:"token"`
	User  *model.User `json:"user"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// The `File` type, represents the response of uploading a file.
type File struct {
	Name        string `json:"name"`
	ContentType string `json:"contentType"`
}

type FileInput struct {
	File graphql.Upload `json:"file"`
	Path string         `json:"path"`
}

type ShareInput struct {
	Path       string `json:"path"`
	ExpireDays int    `json:"expireDays"`
}
