name: Docker Image CI

on:
  push:
    tags:
      - v*
  
env:
  DOCKER_REG: littlefisher0/cosdisk

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USR }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PWD }}
    - uses: actions/checkout@v3
    - name: Generate App Version
      run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
      uses: docker/build-push-action@v3.0.0
      with:
        push: true
        tags: |
          ${{ env.DOCKER_REG }}:latest
          ${{ env.DOCKER_REG }}:${{ env.APP_VERSION }}
